# Site Info
title: HBLucasKo's blog
tagline: 'for DeepLearning'
description: 'Blog for Deep Learning'
url: http://HBLucasKo.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: KoLucas
  description: <strong>PRML</strong> Pattern Recognition and Machine Learning
  gravatar: 603b107782c23d715da6df90c5e5a290 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/
    github:    https://github.com/HBLucasKo
    #facebook:  https://www.facebook.com/
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:hb_ko@korea.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://HBLucasKo.github.io/public/img/corgi.jpg
  caption: A cute corgi~

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'HBLucasKo-github-io' # leave blank if you don't want disqus

